name: geetaxi
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  cloud_firestore: ^0.14.0
  connectivity: ^0.4.9+3
  google_maps_flutter: ^1.0.2
  outline_material_icons: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Brand-Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
  assets:
    - images/


      